### ISSUE TITLE
i18n for JS in Nashorn

### ISSUE THREAD

**Issue by plata** [adrienrn/jsgettext#2]
Is it possible to use jsgettext to translate Strings in JavaScript executed by Nashorn? I'm having issues because jsgettext is using `document` which does not exist in a Nashorn context.

**Comment by adrienrn** [comment]
I discover Nashborn but I can see the problem with the missing `document`

As stated in the intro, this whole project does not belong to me. It's © Joshua I. Miller that I used when it was still available on sourceforge and I took the liberty to create a github with it when the project disappeared.

I'm sure it can be tweaked or improved to work in non-browser environment. If you're willing to submit a PR, I'll gladly integrate it in here.

You might be interested in something like this: https://github.com/alexanderwallin/node-gettext

**Comment by plata** [comment]
Thanks for the reply. I guess we'll look for another solution then (we`re also not using Node.js which is required by node-gettext).
